### PR TITLE
Added fallback for mysql-client when using MariaDB

### PR DESCRIPTION
**Pull request by JasMich**
I resolved an issue when using a MariaDB server.

### CODE REVIEW

**Comment by JasMich** [comment]
Okay, now using `type` instead.

**Comment by MysticRyuujin** [comment]
I wasn't really asking you to change it, just looking for a best practice. It think if it had been me doing it off the top of my head, I'd have gone with a "which" statement to see if it was in the path? Do you have rational for hash vs type vs something else?

**Comment by JasMich** [comment]
It actually doesn't matter that much whether to use `hash`, `command`, `type` or `which`.

**Comment by MysticRyuujin** [comment]
I'll merge for now, Google later. Cheers.

**Comment by MysticRyuujin** [comment]
For my own education:

https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script

which is the least efficient with `command -v <the_command>` being the safest to use.

Best recommendation appears to be `[ -x "$(command -v foo)" ]`

**Pull request merged**
