### PR TITLE
Create guac-install-totp.sh

### PR DESCRIPTION
**Pull request by CountPickering**
I modified the guac-install.sh script to build from git sources and include the totp extension that will allow two factor authentication using the Google Authenticator app.  I tested this using a fresh install of Ubuntu 16.04 and Debian 9.4.

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
Would you be willing to switch to a command line installation switch and just edit the main script with a few if statements?

I'd much rather maintain one script, and provide an option to install the extension and/or build source.

If you are not up for it I could try to do it myself based on this, if I find the time.

**Comment by CountPickering** [comment]
That sounds like a good plan.  I will give it a go.

**Comment by bmullan** [comment]
@CountPickering - last post on this was in March.   I'm curious as how much progress was made?

thanks
brian

**Comment by Xyvir** [comment]
Has this Google Authenticator optional flag been added? I don't seen anything in the readme about it. I would be interested in using this feature.

-Tyler

**Comment by MysticRyuujin** [comment]
I believe that with the addition of the totp in the latest version, and with it being an optional flag now. This PR is no longer required. Is that correct?

**Comment by CountPickering** [comment]
PR is no longer required.

**Pull request closed without merging**
