### PR TITLE
Updated to version 1.2.0 and added missing libavformat-dev package.

### PR DESCRIPTION
**Pull request by SoulSeekkor**
Updated to update/install 1.2.0 and to include an additional package that was missing.

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
Good placeholder until I (or someone else) gets mariadb working

**Comment by SoulSeekkor** [comment]
Thanks @MysticRyuujin !

**Comment by MysticRyuujin** [comment]
No, no, thank you. I've been struggling with the mariadb crap for a few days, I'm grateful for your contribution, I should have just updated it like this and then dealt with it.

I'm have strange issues with TOTP when using mariadb Java connector, I might just give up for now lol

**Comment by SoulSeekkor** [comment]
That does sound odd, wouldn't think the TOTP would be impacted by the database being used?  I think I may have removed the test container I had but it's super easy to spin up another to try it out, I do have a (remote) mariadb server already running I could try it against!  I can give it a shot too if I find the time.

**Pull request merged**
