### PR TITLE
Mostly Typo Fixes

### PR DESCRIPTION
**Pull request by brandonlichtenwalner**
figured I'd share my nitpicking changes

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
I have no issues with any of this except for maybe the capitalization of "GUACD" as it's not capitalized anywhere else including the manual or GitHub repo. It's always "guacd" but whatever.

**Comment by brandonlichtenwalner** [comment]
IIRC I actually changed it to lowercase *from* all caps. New to actually
collaborating on Github, so I hope it was mostly well received. Great
script, btw!

I'm hoping can carve out some time and get a little ambitious and try to
add some stuff to put guac behind an apache or nginx reverse proxy with TLS.

**Comment by MysticRyuujin** [comment]
Yeah I edited the comment to say nevermind I'm dumb :)

I have a "script" that does that plus "Let's Encrypt" on my website, it
probably wouldn't be too hard to modify it to meet your needs...

**Comment by brandonlichtenwalner** [comment]
Awesome. I found it and am definitely going to check it out!

**Pull request merged**
