### PR TITLE
Updated to support guacamole 1.4.0

### PR DESCRIPTION
**Pull request by SoulSeekkor**
Updated for the new version, also updated the guac-install-server.sh a bit, make sure I didn't do anything that would mess it up but I wanted to get it slightly in parity with the regular install script.

Have to review packages yet, I think I saw some potential to add support there, just have to find the time.  I tested the upgrade of my existing 1.3.0 guac to this and it looks to be working fine.

### CODE REVIEW

**Comment by SoulSeekkor** [comment]
This might close #207 as well, that issue is probably unrelated to the version update but don't know for sure.

**Review by MysticRyuujin — APPROVED** [review]

**Comment by aroundmyroom** [comment]
I hope for others that it will work. I took a backup and used the upgrade scripts. No errors during the upgrade, but no way for me getting a remote session work. Even no log output was seen about the error. 

For me worked the previous installation script by changing the 1.3.0 to 1.4.0 and nothing more (and making sure the database dump was reimported again, for my 20 rdp configurations still no clue as syslog and catalina.log does not provide enought debug data.

So my #207 can be closed as I have a working 1.4.0. but in a different way and as I always say: if it works, it works and keep your fingers off it ;)

**Comment by b0se** [comment]
mhm...for me the same problem like @aroundmyroom . I tried the update to 1.4.0 script in another guacamole system. The update process works fine. But i cant connect to my rdp sessions. 

The tomcat Error Log says:
[https-openssl-nio-8443-exec-7] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: java.net.ConnectException: Connection refused (Connection refused)
[https-openssl-nio-8443-exec-6] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused (Connection refused)

But with 1.3.0 it works fine.

**Comment by aroundmyroom** [comment]
That was the exact error I got when I used the update script initially for 1.3.0 where I altered the version number. 
With the new update script I used yesterday I got totally no output in the log files, but issue was the same

For me only worked: 
dump the content of the guacamole_db in a file, then do the installation and after installation import the data back into the gaucamole db restart services and up you go for 1.4.0 with working remote sessions you had.

Did not test it with the new installation script. 

btw I do not like docker but I can understand that it is much more easier to maintain for the developer. But for me as user it gives me always issues on the cli part ;)

**Comment by aroundmyroom** [comment]
@b0se @SoulSeekkor @MysticRyuujin I found the issue 

version 1.3.0 works without the need of /etc/guacamole/guacd.conf but 1.4.0 does need this config file

it has to contain this content

```
[server]
bind_host = 0.0.0.0
bind_port = 4822
[server]
bind_host = 0.0.0.0
bind_port = 4822
```
this file is created when using the installation script but there is no check if this file is present when upgrading from 1.3.0 to 1.4.0

I just upgraded 1.3.0 to 1.4.0 by use of the old upgrade script only changing 1.3.0 to 1.4.0 and adding the guacd.conf
than restart the services 
systemctl restart guacd.service 
systemctl restart tomcat9.service

and its working

**Comment by b0se** [comment]
i found another soultion. i've checked the installation of my working 1.4.0 system. then i was wondering, that the guacd service is Listening on host 127.0.0.1, port 4822. On the other (not working system), the service is listening on ::1, port 4822. So i diabled ipv6 on the system..and restarted the service..and voila...is working :)

**Comment by aroundmyroom** [comment]
@b0se I have seen this when it checked it as well .. did not know that ::1 referred to ipv6 cause I see that IPv6 was enabled on my server as well but adding the config file solved it without disabling ipv6 .. (no idea why I have it enabled).

**Pull request merged**
