### PR TITLE
Upgrade 1.5

### PR DESCRIPTION
**Pull request by go-ten**

### CODE REVIEW

**Comment by MysticRyuujin** [comment]
Works without additional changes? You tested?

**Comment by go-ten** [comment]
Hi, Not tested yet.

**Comment by go-ten** [comment]
Hello, I just tested it. It works without any problem.

**Comment by phatdo1819** [comment]
Same here, I tested on Ubuntu 20.04 and it seems working without any problem.
Haven't tested yet on other distros.

**Comment by go-ten** [comment]
On my side I just noticed that the history is empty. I just have the time spent on the sessions.

**Pull request merged**
